### PR TITLE
Humble port

### PR DESCRIPTION
**Pull request by mcbed**
Ported the packages as-is to work in Humble. Based on PR #7.

### CODE REVIEW

**Comment by peterdavidfagan** [comment]
@mcbed have you tested running the updated code from this pr on the Panda? 

Running ROS2 Humble on our system would be very helpful as it would enable us to leverage recent updates to the MoveIt library. I am happy to contribute to this pr where possible if parts need to be updated.

**Comment by mcbed** [comment]
@marcbone, could you allow me to run the CI on this PR ?

**Comment by marcbone** [comment]
looking at the most recent changes. I guess the errors come from introducing the captures in the lambdas. Also the "not"s were also replaced in the strings. This should be reverted

**Comment by peterdavidfagan** [comment]
@marcbone @mcbed I think from Humble onwards ros2-control uses the https://github.com/PickNikRobotics/generate_parameter_library to generate parameters. Maybe this is part of the issue I am facing with this current set of code as the `joint_effort_trajectory_controller` follows a different design pattern. I am still reading through ROS2 control docs and the code but would it make sense to switch to the official `joint_trajectory_controller` from ROS distros starting at Humble onwards?

https://github.com/ros-controls/ros2_controllers/tree/humble/joint_trajectory_controller/src

**Comment by mcbed** [comment]
now all should build as CI failed because of format tests. @marcbone, can you run CI again ?

**Comment by marcbone** [comment]
@peterdavidfagan about the joint_trajectory_controller, the reason I copied it was that [this PR](https://github.com/ros-controls/ros2_controllers/pull/225) was still open at that time. Also there was the issue that the controller would not keep its initial pose before you send him a goal. It would instead only send zero torques. I modified this to use the starting pose as goal pose when the controller is started. I am not sure whether this is now also in the upstream controller. You should check this before you start using it.

**Comment by destogl** [comment]
> Also there was the issue that the controller would not keep its initial pose before you send him a goal. It would instead only send zero torques. I modified this to use the starting pose as goal pose when the controller is started.

This could still be an issue. Nevertheless, we are glad to fix this if we get a PR :)

**Comment by peterdavidfagan** [comment]
> This could still be an issue. Nevertheless, we are glad to fix this if we get a PR :)

Happy to work on this, still reading the code and upramping but I would be happy to work towards submitting a PR with these changes.

**Comment by marcbone** [comment]
@peterdavidfagan If you want to work on this, [this is the commit](https://github.com/frankaemika/franka_ros2/commit/8671588f2fe91f925848c8aa112cc050acc770e1#diff-14bf2d9185d549c84286510ef2771e8dd01c2e6d8e05b8dae3fbeb52313c401b) where I fixed it.

**Comment by peterdavidfagan** [comment]
@marcbone changes submitted in [pr](https://github.com/ros-controls/ros2_controllers/pull/531) to the ros2_controllers repository. I've also add another [pr](https://github.com/mcbed/franka_ros2/pull/3) for the current Humble port. Before running the controller on a real-robot do you have any guidance on avoiding damage to the motors etc.? 

@destogl is there a recommended way to test the changes I make to controller software in ros2_controllers? I presume I should run tests defined [here](https://github.com/peterdavidfagan/ros2_controllers/tree/jtc_fix_initial_pose/joint_trajectory_controller/test). 

Note: I am also happy to open a separate pr that adds support for MoveItConfigsBuilder, I'll be developing this code anyway for our setup so happy to add this.

**Comment by marcbone** [comment]
@peterdavidfagan What I really like about the FCI is that you cannot damage the robot by sending out wrong commands (as long as you are not moving it into something like a chainsaw, or fullspeed into the ground). It will may make motions that look scary to you but the robot will reject any commands that would harm the motors. Just be quick with the user stop button if the robot tries to move itself into an object. What you also can do is to call "robot->setCollisionBehavior(...)" [after this line](https://github.com/frankaemika/franka_ros2/blob/419beace847b69d4743657a5a25964cab7446bb8/franka_hardware/src/robot.cpp#L34) and use very low values. This will make the robot stop faster if it collides with something (by detecting a collision earlier).

**Comment by peterdavidfagan** [comment]
Awesome thanks @marcbone this is really reassuring and what I was hoping to here. 

> (as long as you are not moving it into something like a chainsaw, or fullspeed into the ground)

I can confirm that there are no chainsaws in the vicinity of our robot, we do have a ground plane though :). 

> What you also can do is to call "robot->setCollisionBehavior(...)" [after this line](https://github.com/frankaemika/franka_ros2/blob/419beace847b69d4743657a5a25964cab7446bb8/franka_hardware/src/robot.cpp#L34) and use very low values. This will make the robot stop faster if it collides with something (by detecting a collision earlier).

Thanks for this tip and the support in helping answer these queries.

**Comment by peterdavidfagan** [comment]
Works with Humble now, thanks @marcbone @destogl @mcbed for the help with this.

https://user-images.githubusercontent.com/42982057/220659804-cc3e76c1-4b14-4678-8498-3f23055a7e6d.MOV

**Comment by craig-sony** [comment]
+1 Eagerly awaiting this merge. Thanks.

**Comment by BarisYazici** [comment]
> +1 Eagerly awaiting this merge. Thanks.

We are working on it @craig-sony

**Comment by tingelst** [comment]
I have a working setup with a Panda on Humble. With the ported `joint_effort_trajectory_controller` the motion is smooth and everything works. With the upstream `joint_trajectory_controller` from `ros2_controllers`, however, I am getting a very jerky motion with the same PID gains. I have tested the `humble` branch, as well as the different PRs related to the jtc.

Have you seen this behavior on your setups?

**Comment by drewskoots** [comment]
Yes! I have also started to notice this problem while using Moveit! and thought my motion planning was the issue. AFAIK the default move it controller also uses the JTC to actually perform the motion.

**Comment by BarisYazici** [comment]
We have released the source code of the humble port! We kept the original commits from @mcbed and extended with unit testing. Thanks a lot for your contribution! 💯 
Humble is now the default branch at franka_ros2 repo. Please take a look and test it with your own setup. If there is no issue, we could close this PR.

**Comment by christian-rauch** [comment]
> Humble is now the default branch at franka_ros2 repo. Please take a look and test it with your own setup. If there is no issue, we could close this PR.

@BarisYazici Since this is incompatible with foxy, could you rename the `develop` branch to `foxy` to indicate that this is the old version for the previous LTS version?

**Comment by BarisYazici** [comment]
> @BarisYazici Since this is incompatible with foxy, could you rename the `develop` branch to `foxy` to indicate that this is the old version for the previous LTS version?

We will push a new branch named `foxy` to avoid having upstream deleted for the users on `develop` branch.

**Pull request closed without merging**
